---
title: "Configuration of services running in a container"
date: 2023-03-07T09:39:58+05:30
draft: false
description: This guide will explain how to configure the services running in containers for your tests using Testcontainers.
repo: https://github.com/testcontainers/tc-guide-configuration-of-services-running-in-container
languages:
  - Java
tags:
  - postgresql
  - localstack
---
:toc:
:toclevels: 2
:codebase: https://raw.githubusercontent.com/testcontainers/tc-guide-configuration-of-services-running-in-container/main

In this guide you will learn how to

* Initialize containers by copying files into the containers
* Run supporting commands inside docker containers using `execInContainer()`

== Prerequisites
* Java 17+
* Your favorite IDE (Intellij IDEA, Eclipse, NetBeans, VS Code)
* A Docker environment supported by Testcontainers https://www.testcontainers.org/supported_docker_environment/

== What we are going to achieve in this guide
We are going to use a Postgres container and create the database schema using SQL scripts
by copying them into the container. Also, we are going to learn how we can initialize
https://localstack.cloud/[LocalStack] containers to create S3 buckets by executing commands inside the container.

== Getting Started
Create a new Java project with the Maven or Gradle build tool and add the following dependencies.

[source,groovy]
----
dependencies {
   implementation "org.postgresql:postgresql:42.7.3"
   implementation "ch.qos.logback:logback-classic:1.5.6"

   testImplementation(platform("org.testcontainers:testcontainers-bom:1.19.8"))
   testImplementation "software.amazon.awssdk:s3:2.21.46"
   // Reason for including AWS Java SDK V1: https://github.com/testcontainers/testcontainers-java/issues/1442
   testImplementation "com.amazonaws:aws-java-sdk-s3:1.12.461"
   testImplementation "org.junit.jupiter:junit-jupiter"
   testImplementation "org.testcontainers:junit-jupiter"
   testImplementation "org.testcontainers:postgresql"
   testImplementation "org.testcontainers:localstack"
}
----

For complete code please refer to the GitHub repository https://github.com/testcontainers/tc-guide-configuration-of-services-running-in-container

== Initializing the container by copying files into it

While using Testcontainers for testing, sometimes we need to initialize the container (or the application within the container)
by placing files in a certain location within the container.

For example, while using the Postgres database you may want to create the database schema using SQL scripts before running your tests.
You can initialize the Postgres database within the Docker container by placing the SQL scripts in the */docker-entrypoint-initdb.d* directory.

Let us create a database schema creation SQL script *init-db.sql* in *src/test/resources* directory.

[source,sql]
----
include::{codebase}/src/test/resources/init-db.sql[]
----

Now, let’s write a test using the Testcontainers Postgres module.

[source,java]
----
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.MountableFile;

@Testcontainers
class CustomerServiceTest {

   @Container
   static PostgreSQLContainer<?> postgres =
           new PostgreSQLContainer<>("postgres:16-alpine")
                .withCopyFileToContainer(
                    MountableFile.forClasspathResource(
                        "init-db.sql"), "/docker-entrypoint-initdb.d/"
                );

   @Test
   void shouldGetCustomers() {
      ...
   }
}
----

Here we have used the *withCopyFileToContainer(MountableFile mountableFile, String containerPath)* method
to copy the *init-db.sql* file from the classpath into  the */docker-entrypoint-initdb.d/* directory within.
Now when you try to run the test, Testcontainers will spin up a Postgres Docker container with the SQL  scripts
copied into */docker-entrypoint-initdb.d/* directory, where they will be executed automatically before running your tests.
And so you can use those tables from your tests.

We can also copy files from any path on the host using *MountableFile.forHostPath(String path)* as follows:

[source,java]
----
static PostgreSQLContainer<?> postgres =
       new PostgreSQLContainer<>("postgres:16-alpine")
        .withCopyFileToContainer(
                MountableFile.forHostPath("/host/path/to/init-db.sql"),
                "/docker-entrypoint-initdb.d/"
        );
----

== Initializing the container by executing commands inside container

Some Docker containers provide CLI tools to perform various actions by running commands within the container.
While using Testcontainers, we may want to perform some initialization tasks before running our tests.

You can use the *container.execInContainer(String... command)* API to run any available command inside a running container.

For example, Testcontainers provides the LocalStack module which can be used for testing AWS Service integrations.
Let's suppose we are testing the scenario of a file upload into a S3 bucket.
Here we may want to create the S3 bucket before running the tests.

Let us see how we can use the LocalStack module, create a S3 bucket using *execInContainer()* and
assert that the bucket exists in your test.

[source,java]
----
include::{codebase}/src/test/java/com/testcontainers/demo/LocalStackTest.java[lines="22..45,54..77"]
----

Here we have created a S3 bucket by running the command *"awslocal s3 mb s3://bucketName"* via *localStack.execInContainer(...)*.
*"awslocal"* is a command line tool provided as part of the LocalStack Docker image.
Similarly, you can run any arbitrary valid command inside the running container.

We can also run any command and get the output and exit code as follows:

[source,java]
----
Container.ExecResult execResult =
    localStack.execInContainer("awslocal", "s3", "ls");
String stdout = execResult.getStdout();
int exitCode = execResult.getExitCode();
assertTrue(stdout.contains(bucketName));
assertEquals(0, exitCode);
----

[NOTE]
The *withClasspathResourceMapping(), withCopyFileToContainer(), execInContainer()* methods are inherited from *GenericContainer*.
So they are available for all Testcontainers modules extending *GenericContainer* as well.

== Summary
We have learned how we can configure the test dependency containers using Testcontainers by copying files
into containers and executing commands inside the running containers. These container customization features
help in setting up the containers in a desired state for our test scenarios.

To learn more about Testcontainers visit http://testcontainers.com

== Further Reading
* https://testcontainers.com/guides/getting-started-with-testcontainers-for-java/[Getting started with Testcontainers for Java]
* https://www.testcontainers.org/quickstart/junit_5_quickstart/[Testcontainers JUnit 5 QuickStart]
* https://www.testcontainers.org/modules/databases/postgres/[Testcontainers Postgres Module]
* https://www.testcontainers.org/modules/localstack/[Testcontainers LocalStack Module]
